#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_content_filter:
    <<:
      # Building the image
      &mib_content_filter
      image: "mib-content_filter:latest"
      build:
        context: .
        dockerfile: Dockerfile

    ports:
      - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migration
    
  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_content_filter
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure
    depends_on:
      - db

# Declaring all volumes
volumes:
  pgdata: null # for maintaing db data
