# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContentFilter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, filter_id: int=None, filter_name: str=None, filter_active: bool=False):  # noqa: E501
        """ContentFilter - a model defined in Swagger

        :param filter_id: The filter_id of this ContentFilter.  # noqa: E501
        :type filter_id: int
        :param filter_name: The filter_name of this ContentFilter.  # noqa: E501
        :type filter_name: str
        :param filter_active: The filter_active of this ContentFilter.  # noqa: E501
        :type filter_active: bool
        """
        self.swagger_types = {
            'filter_id': int,
            'filter_name': str,
            'filter_active': bool
        }

        self.attribute_map = {
            'filter_id': 'filter_id',
            'filter_name': 'filter_name',
            'filter_active': 'filter_active'
        }
        self._filter_id = filter_id
        self._filter_name = filter_name
        self._filter_active = filter_active

    @classmethod
    def from_dict(cls, dikt) -> 'ContentFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContentFilter of this ContentFilter.  # noqa: E501
        :rtype: ContentFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filter_id(self) -> int:
        """Gets the filter_id of this ContentFilter.

        id of content filter  # noqa: E501

        :return: The filter_id of this ContentFilter.
        :rtype: int
        """
        return self._filter_id

    @filter_id.setter
    def filter_id(self, filter_id: int):
        """Sets the filter_id of this ContentFilter.

        id of content filter  # noqa: E501

        :param filter_id: The filter_id of this ContentFilter.
        :type filter_id: int
        """
        if filter_id is None:
            raise ValueError("Invalid value for `filter_id`, must not be `None`")  # noqa: E501

        self._filter_id = filter_id

    @property
    def filter_name(self) -> str:
        """Gets the filter_name of this ContentFilter.

        name of content filter  # noqa: E501

        :return: The filter_name of this ContentFilter.
        :rtype: str
        """
        return self._filter_name

    @filter_name.setter
    def filter_name(self, filter_name: str):
        """Sets the filter_name of this ContentFilter.

        name of content filter  # noqa: E501

        :param filter_name: The filter_name of this ContentFilter.
        :type filter_name: str
        """
        if filter_name is None:
            raise ValueError("Invalid value for `filter_name`, must not be `None`")  # noqa: E501

        self._filter_name = filter_name

    @property
    def filter_active(self) -> bool:
        """Gets the filter_active of this ContentFilter.

        status of the content filter  # noqa: E501

        :return: The filter_active of this ContentFilter.
        :rtype: bool
        """
        return self._filter_active

    @filter_active.setter
    def filter_active(self, filter_active: bool):
        """Sets the filter_active of this ContentFilter.

        status of the content filter  # noqa: E501

        :param filter_active: The filter_active of this ContentFilter.
        :type filter_active: bool
        """
        if filter_active is None:
            raise ValueError("Invalid value for `filter_active`, must not be `None`")  # noqa: E501

        self._filter_active = filter_active
