"""empty message

Revision ID: 360b9d7bbf0f
Revises: 
Create Date: 2021-11-29 19:49:17.623194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360b9d7bbf0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_filter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.Column('words', sa.Unicode(length=128), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_filter')
    # ### end Alembic commands ###
