"""empty message

Revision ID: 8a47ec8d95e4
Revises: 
Create Date: 2021-12-08 16:32:52.720695

"""
from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision = '8a47ec8d95e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cf = op.create_table('content_filter',
    sa.Column('filter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_name', sa.Unicode(length=128), nullable=True),
    sa.Column('filter_words', sa.Text(), nullable=True),
    sa.Column('filter_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_table('user_content_filter',
    sa.Column('filter_id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_id_user', sa.Integer(), nullable=True),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('filter_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['content_filter.filter_id'], ),
    sa.PrimaryKeyConstraint('filter_id_key')
    )
    # ### end Alembic commands ###
    word_list = []
    file1 = open('swagger_server/badwords.txt', 'r')
    Lines = file1.readlines()
    for line in Lines:
        word_list.append(line.strip())
    word_list.sort(key=lambda el: -len(el))
    op.bulk_insert(cf,
        [
            {
                'filter_id':0,
                'filter_name':'Default',
                'filter_words':json.dumps(word_list),
                'filter_private':False
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_content_filter')
    op.drop_table('content_filter')
    # ### end Alembic commands ###
