"""empty message

Revision ID: fff0f6eb0d0c
Revises: 
Create Date: 2021-11-29 22:51:21.689036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff0f6eb0d0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_filter',
    sa.Column('filter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_name', sa.Unicode(length=128), nullable=True),
    sa.Column('filter_words', sa.Unicode(length=128), nullable=True),
    sa.Column('filter_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_table('user_content_filter',
    sa.Column('filter_id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_id_user', sa.Integer(), nullable=True),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('filter_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['content_filter.filter_id'], ),
    sa.PrimaryKeyConstraint('filter_id_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_content_filter')
    op.drop_table('content_filter')
    # ### end Alembic commands ###
